<?php
/**
 * Generated by PHPUnit_SkeletonGenerator on 2017-04-23 at 18:46:37.
 */
require_once '..\BaseDeDatos\conexion_bd.php';
class conexion_bdTest extends PHPUnit_Framework_TestCase
{
    /**
     * @covers conexion_bd::conectar
     * @todo   Implement testConectar().
     */
    public function testConectar()
    {
         $expected = TRUE;
         $actual = null;
         
         conexion_bd::conectar();
         $actual = conexion_bd::getConnected();
         
         $this->assertEquals($expected, $actual,"successful connection");
    }

    /**
     * @covers conexion_bd::desconectar
     * @todo   Implement testDesconectar().
     */
    public function testDesconectar()
    {
           $expected = FALSE;
           
           conexion_bd::desconectar();
           $actual = conexion_bd::getConnected();
           
           $this->assertEquals($expected, $actual);
    }
}
