<?php

/**
 * Generated by PHPUnit_SkeletonGenerator on 2017-04-23 at 20:15:55.
 */
//Entity unit of testing
require_once '..\BaseDeDatos\MuseoGestion.php';
//Dependency used 
require_once '..\BaseDeDatos\Museo.php';
require_once '..\BaseDeDatos\conexion_bd.php';

class MuseoGestionTest extends PHPUnit_Framework_TestCase {

    /**
     * @var MuseoGestion
     */
    protected $gestor;
    protected $conexion;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->conexion = conexion_bd::conectar();
        $this->gestor = new MuseoGestion();
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        conexion_bd::desconectar();
    }

    /**
     * @covers MuseoGestion::registrarMuseo
     * @todo   Implement testRegistrarMuseo().
     */
    public function testRegistrarMuseo() {
        $actual = TRUE;

        $museo = new Museo('9823431', 'Museo de Arte Antonio Nariño');
        $expected = $this->gestor->registrarMuseo($museo, $this->conexion);

        $this->assertEquals($expected, $actual);
    }

    /**
     * @covers MuseoGestion::eliminarMuseo($nit, $conexion)
     * @todo   Implement testEliminarMuseo().
     * @depends testRegistrarMuseo
     */
    public function testEliminarMuseo() {
        $actual = TRUE;
        $museo = new Museo('9823431', 'Museo de Arte Antonio Nariño');

        $expected = $this->gestor->eliminarMuseo($museo->getNit(), $this->conexion);

        $this->assertEquals($expected, $actual);
    }

    /**
     * @covers MuseoGestion::actualizarMuseo($nit, $museo, $conexion)
     * @todo   Implement testActualizarMuseo().
     * @depends testRegistrarMuseo
     */
        public function testActualizarMuseo() 
        {
            $actual = TRUE;
            $museo = new Museo(9823432, 'Museo de Arte Antonio Nariño');
            $nit = 9823431;

            $expected = $this->gestor->actualizarMuseo($nit, $museo, $this->conexion);

            $this->assertEquals($expected, $actual);    
        }
}
