<?php

/**
 * Generated by PHPUnit_SkeletonGenerator on 2017-05-02 at 02:54:13.
 */
require_once '..\BaseDeDatos\conexion_bd.php';
require_once '..\BaseDeDatos\Restauradores.php';
require_once '..\BaseDeDatos\RestauradoresGestion.php';

class RestauradoresGestionTest extends PHPUnit_Framework_TestCase {

    /**
     * @var RestauradoresGestion
     */
    protected $gestor;
    protected $conexion;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->gestor = new RestauradoresGestion();
        $this->conexion = conexion_bd::conectar();
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        conexion_bd::desconectar();
    }

    /**
     * @covers RestauradoresGestion::registrarRestaurador($restaurador, $con)
     * @todo   Implement testRegistrarRestaurador().
     */
    public function testRegistrarRestaurador() {
        $expected = TRUE;

        $restaurador = new Restauradores(189913532, 'Juan Carlos', 3130912313, 'juancarlos@lucky.com', 'Henao');
        $actual = $this->gestor->registrarRestaurador($restaurador, $this->conexion);

        $this->assertEquals($expected, $actual);
    }

    /**
     * @covers RestauradoresGestion::registrarRestaurador($restaurador, $con)
     * @todo   Implement testRegistrarRestaurador().
     *  @depends testRegistrarRestaurador
     */
    public function testEliminarRestaurador() {
        $expected = TRUE;

        $cedula = 189913532;
        $actual = $this->gestor->eliminarRestaurador($cedula, $this->conexion);

        $this->assertEquals($expected, $actual);
    }

    /**
     * @covers RestauradoresGestion::actualizarRestaurador($restaurador, $cedula, $con)
     * @todo  Implement testActualizarRestaurador().
     * @depends testRegistrarRestaurador
     */
    public function testActualizarRestaurador() {
        $expected = TRUE;

        $cedula = 189913532;
        $restaurador = new Restauradores(189913100, 'Juan Ruiz', 3172329001, 'velasquez@lucky.com', 'Velasquez');

        $actual = $this->gestor->actualizarRestaurador($restaurador, $cedula, $this->conexion);

        $this->assertEquals($expected, $actual);
    }

}
